import { useState } from 'react';
import {
  AutomationExportFormat,
  AutomationRunSummary,
  MAX_AUTOMATION_TURNS,
  MIN_AUTOMATION_TURNS,
} from '../../../shared/types/automation';
import { SamplerParams } from '../../../shared/types/chat';
import { FIELD_LIMITS } from '../../../shared/fieldLimits';
import { UseAutomation } from '../../hooks/useAutomation';
import LimitedTextarea from '../LimitedTextarea';

interface Props {
  automation: UseAutomation;
  conversationId: string;
  characterId: string;
  characterName: string;
  personaId: string;
  personaName: string;
  model: string;
  samplers: Partial<SamplerParams>;
  isGroup: boolean;
  /** A reply is being generated by the chat itself right now. */
  chatBusy: boolean;
}

const STATUS_LABEL: Record<AutomationRunSummary['status'], string> = {
  running: 'Running',
  completed: 'Completed',
  stopped: 'Stopped',
  failed: 'Failed',
  interrupted: 'Interrupted',
};

function formatWhen(iso: string): string {
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? iso : date.toLocaleString();
}

/**
 * The right sidebar's Automate tab: plays both sides of this conversation for a set number of
 * turns, then keeps the full log -- exportable from the list below. The persona's lines are
 * drafted by the same model call as the composer's "Suggest reply", so what gets tested is the
 * real chat path. Everything is saved into the open conversation like normal messages.
 */
export default function AutomationPanel({
  automation,
  conversationId,
  characterId,
  characterName,
  personaId,
  personaName,
  model,
  samplers,
  isGroup,
  chatBusy,
}: Props) {
  const [turns, setTurns] = useState(10);
  const [directions, setDirections] = useState('');
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const { active, phase, automatingHere } = automation;

  const blocker = isGroup
    ? 'Automated runs support one-character conversations only.'
    : !characterId
      ? 'Pick a character first.'
      : !personaId
        ? 'Pick a persona on the Settings tab -- it plays the user side.'
        : !model
          ? 'Pick a model first.'
          : active && !automatingHere
            ? 'Another automated run is in progress.'
            : chatBusy
              ? 'Wait for the current reply to finish.'
              : null;

  const turnsValid = Number.isInteger(turns) && turns >= MIN_AUTOMATION_TURNS && turns <= MAX_AUTOMATION_TURNS;

  const handleStart = () => {
    setNotice(null);
    void automation.start({
      conversationId,
      characterId,
      personaId,
      model,
      turns,
      directions: directions.trim() || undefined,
      samplers,
    });
  };

  const handleExport = async (runId: string, format: AutomationExportFormat) => {
    setNotice(null);
    try {
      const result = await window.electronAPI.automation.export(runId, format);
      if (result.saved) setNotice(`Saved to ${result.path}`);
    } catch (exportError) {
      setNotice(`Export failed: ${(exportError as Error).message}`);
    }
  };

  const handleDelete = async (runId: string) => {
    setConfirmDeleteId(null);
    try {
      await window.electronAPI.automation.delete(runId);
      await automation.refreshRuns();
    } catch (deleteError) {
      setNotice(`Delete failed: ${(deleteError as Error).message}`);
    }
  };

  const phaseText =
    phase === 'persona'
      ? `Writing ${personaName || 'the persona'}'s line…`
      : phase === 'character'
        ? `${characterName || 'The character'} is replying…`
        : 'Working…';

  return (
    <div className="chat-settings-panel automation-panel">
      <section className="chat-settings-section">
        <h3 className="chat-settings-section-title">Automate</h3>
        <p className="automation-help">
          Plays both sides of this conversation: {personaName || 'your persona'} is written by the model, then{' '}
          {characterName || 'the character'} replies, over and over. Everything is saved here like normal messages,
          and a full log is kept for export.
        </p>

        {automatingHere && active ? (
          <>
            <div className="automation-progress" role="status">
              <strong>
                Turn {Math.min(active.completedTurns + 1, active.requestedTurns)} of {active.requestedTurns}
              </strong>
              <span>{phaseText}</span>
            </div>
            <button type="button" className="btn btn-danger" onClick={() => void automation.stop()}>
              Stop
            </button>
            <p className="automation-help">The chat is locked while a run is going. Stopping keeps everything so far.</p>
          </>
        ) : (
          <>
            <label className="chat-settings-field">
              <span className="chat-settings-field-label">Turns (a persona line plus a reply)</span>
              <input
                type="number"
                min={MIN_AUTOMATION_TURNS}
                max={MAX_AUTOMATION_TURNS}
                value={Number.isNaN(turns) ? '' : turns}
                onChange={(e) => setTurns(e.target.value === '' ? NaN : Number(e.target.value))}
              />
            </label>
            <label className="chat-settings-field">
              <span className="chat-settings-field-label">Directions for every reply (optional)</span>
              <LimitedTextarea
                value={directions}
                onChange={(e) => setDirections(e.target.value)}
                limit={FIELD_LIMITS.directions}
                rows={3}
                placeholder="e.g. Keep the scene on the ship."
              />
            </label>
            <button
              type="button"
              className="btn btn-primary"
              disabled={Boolean(blocker) || !turnsValid}
              onClick={handleStart}
            >
              Start
            </button>
            {blocker && <p className="automation-help automation-blocker">{blocker}</p>}
            {!turnsValid && (
              <p className="automation-help automation-blocker">
                Turns must be a whole number from {MIN_AUTOMATION_TURNS} to {MAX_AUTOMATION_TURNS}.
              </p>
            )}
          </>
        )}

        {automation.error && (
          <div className="chat-banner chat-banner-error">
            {automation.error}
            <button type="button" className="btn" onClick={automation.dismissError}>
              Dismiss
            </button>
          </div>
        )}
        {notice && <p className="automation-help">{notice}</p>}
      </section>

      <section className="chat-settings-section">
        <h3 className="chat-settings-section-title">Past runs</h3>
        {automation.runs.length === 0 && <p className="automation-help">No automated runs yet.</p>}
        <ul className="automation-runs">
          {automation.runs.map((run) => (
            <li key={run.id} className="automation-run">
              <div className="automation-run-head">
                <span className={`automation-status automation-status-${run.status}`}>{STATUS_LABEL[run.status]}</span>
                <span className="automation-run-title">
                  {run.characterName} &amp; {run.personaName}
                </span>
              </div>
              <div className="automation-run-meta">
                {run.completedTurns}/{run.requestedTurns} turns · {run.model} · {formatWhen(run.startedAt)}
              </div>
              {run.error && <div className="automation-run-error">{run.error}</div>}
              {run.status !== 'running' && (
                <div className="automation-run-actions">
                  <button type="button" className="btn" onClick={() => void handleExport(run.id, 'json')}>
                    Export JSON
                  </button>
                  <button type="button" className="btn" onClick={() => void handleExport(run.id, 'md')}>
                    Export Markdown
                  </button>
                  {confirmDeleteId === run.id ? (
                    <>
                      <button type="button" className="btn btn-danger" onClick={() => void handleDelete(run.id)}>
                        Delete log
                      </button>
                      <button type="button" className="btn" onClick={() => setConfirmDeleteId(null)}>
                        Cancel
                      </button>
                    </>
                  ) : (
                    <button type="button" className="btn" onClick={() => setConfirmDeleteId(run.id)}>
                      Delete
                    </button>
                  )}
                </div>
              )}
            </li>
          ))}
        </ul>
        <p className="automation-help">
          Deleting a log does not delete the conversation it was run in. Exported files are plain text, even when
          app encryption is on.
        </p>
      </section>
    </div>
  );
}
