import { useState } from 'react';
import { Link } from 'react-router-dom';
import { MAX_AUTOMATION_TURNS, MIN_AUTOMATION_TURNS } from '../../../shared/types/automation';
import { SamplerParams } from '../../../shared/types/chat';
import { FIELD_LIMITS } from '../../../shared/fieldLimits';
import { UseAutomation } from '../../hooks/useAutomation';
import LimitedTextarea from '../LimitedTextarea';
import AutomationRunList from '../AutomationRunList';

interface Props {
  automation: UseAutomation;
  conversationId: string;
  characterId: string;
  characterName: string;
  personaId: string;
  personaName: string;
  model: string;
  samplers: Partial<SamplerParams>;
  isGroup: boolean;
  /** A reply is being generated by the chat itself right now. */
  chatBusy: boolean;
}

/**
 * The right sidebar's Automate tab: plays both sides of this conversation for a set number of
 * turns, then keeps the full log -- exportable from the list below. The persona's lines are
 * drafted by the same model call as the composer's "Suggest reply", so what gets tested is the
 * real chat path. Everything is saved into the open conversation like normal messages.
 */
export default function AutomationPanel({
  automation,
  conversationId,
  characterId,
  characterName,
  personaId,
  personaName,
  model,
  samplers,
  isGroup,
  chatBusy,
}: Props) {
  const [turns, setTurns] = useState(10);
  const [directions, setDirections] = useState('');
  const [personaDirections, setPersonaDirections] = useState('');

  const { active, phase, automatingHere } = automation;
  const thisChatRuns = automation.runs.filter((run) => run.conversationId === conversationId);

  const blocker = isGroup
    ? 'Automated runs support one-character conversations only.'
    : !characterId
      ? 'Pick a character first.'
      : !personaId
        ? 'Pick a persona on the Settings tab -- it plays the user side.'
        : !model
          ? 'Pick a model first.'
          : active && !automatingHere
            ? 'Another automated run is in progress.'
            : chatBusy
              ? 'Wait for the current reply to finish.'
              : null;

  const turnsValid = Number.isInteger(turns) && turns >= MIN_AUTOMATION_TURNS && turns <= MAX_AUTOMATION_TURNS;

  const handleStart = () => {
    void automation.start({
      conversationId,
      characterId,
      personaId,
      model,
      turns,
      directions: directions.trim() || undefined,
      personaDirections: personaDirections.trim() || undefined,
      samplers,
    });
  };

  const phaseText =
    phase === 'persona'
      ? `Writing ${personaName || 'the persona'}'s line…`
      : phase === 'character'
        ? `${characterName || 'The character'} is replying…`
        : 'Working…';

  return (
    <div className="chat-settings-panel automation-panel">
      <section className="chat-settings-section">
        <h3 className="chat-settings-section-title">Automate</h3>
        <p className="automation-help">
          Plays both sides of this conversation: {personaName || 'your persona'} is written by the model, then{' '}
          {characterName || 'the character'} replies, over and over. Everything is saved here like normal messages,
          and a full log is kept for export.
        </p>

        {automatingHere && active ? (
          <>
            <div className="automation-progress" role="status">
              <strong>
                Turn {Math.min(active.completedTurns + 1, active.requestedTurns)} of {active.requestedTurns}
              </strong>
              <span>{phaseText}</span>
            </div>
            <button type="button" className="btn btn-danger" onClick={() => void automation.stop()}>
              Stop
            </button>
            <p className="automation-help">The chat is locked while a run is going. Stopping keeps everything so far.</p>
          </>
        ) : (
          <>
            <label className="chat-settings-field">
              <span className="chat-settings-field-label">Turns (a persona line plus a reply)</span>
              <input
                type="number"
                min={MIN_AUTOMATION_TURNS}
                max={MAX_AUTOMATION_TURNS}
                value={Number.isNaN(turns) ? '' : turns}
                onChange={(e) => setTurns(e.target.value === '' ? NaN : Number(e.target.value))}
              />
            </label>
            <label className="chat-settings-field">
              <span className="chat-settings-field-label">Directions for the character's replies (optional)</span>
              <LimitedTextarea
                value={directions}
                onChange={(e) => setDirections(e.target.value)}
                limit={FIELD_LIMITS.directions}
                rows={3}
                placeholder="e.g. Keep the scene on the ship."
              />
            </label>
            <label className="chat-settings-field">
              <span className="chat-settings-field-label">
                What {personaName || 'the persona'} is steering toward (optional)
              </span>
              <LimitedTextarea
                value={personaDirections}
                onChange={(e) => setPersonaDirections(e.target.value)}
                limit={FIELD_LIMITS.directions}
                rows={3}
                placeholder="e.g. Wrap this scene up and move on to the next lead."
              />
            </label>
            <button
              type="button"
              className="btn btn-primary"
              disabled={Boolean(blocker) || !turnsValid}
              onClick={handleStart}
            >
              Start
            </button>
            {blocker && <p className="automation-help automation-blocker">{blocker}</p>}
            {!turnsValid && (
              <p className="automation-help automation-blocker">
                Turns must be a whole number from {MIN_AUTOMATION_TURNS} to {MAX_AUTOMATION_TURNS}.
              </p>
            )}
          </>
        )}

        {automation.error && (
          <div className="chat-banner chat-banner-error">
            {automation.error}
            <button type="button" className="btn" onClick={automation.dismissError}>
              Dismiss
            </button>
          </div>
        )}
      </section>

      <section className="chat-settings-section">
        <h3 className="chat-settings-section-title">Runs in this chat</h3>
        <AutomationRunList
          runs={thisChatRuns}
          onChanged={automation.refreshRuns}
          emptyText="No automated runs in this chat yet."
        />
        <p className="automation-help">
          Every run, across all chats, is under <Link to="/settings?tab=automation">Settings → Automated Runs</Link>.
        </p>
      </section>
    </div>
  );
}
